name: CI
on:
  push:
    branches:
      - main

jobs:
  step1:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      
      - name: abc
        env:
          OW_APIHOST: ${{ secrets.OW_APIHOST }}
          OW_AUTH: ${{ secrets.OW_AUTH }}
          OW_NAMESPACE: ${{ secrets.OW_NAMESPACE }}
          OW_IAM_NAMESPACE_API_KEY: ${{ secrets.OW_IAM_NAMESPACE_API_KEY }}

        run: |
          npm i
          node app
          npm run d
